# Generated by Django 3.2.3 on 2021-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetZone', '0002_event_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trust_index',
            field=models.IntegerField(null=True),
        ),
    ]
