# Generated by Django 3.2.3 on 2021-11-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetZone', '0003_alter_user_trust_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trust_index',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
